[package]
name = "anthill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = { version = "1.0.21", features = ["serde"] }
ant-metadata = { path = "../ant-metadata" }
serde = "1.0.196"
serde_json = "1.0.112"
tracing = "0.1.40"
cargo = "0.72.2"
command-macros = "0.2.9"
tokio = { version = "1.35.1", features = ["tokio-macros", "full"] }
anyhow = "1.0.79"
cargo_metadata = "0.17.0"
