global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "node"

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets:
          # ANT_WORKER_NODE_METRICS_EXPORTER_PORT
          - "antworker001.hosts.typesofants.org:3241"
          - "antworker003.hosts.typesofants.org:3241"
          - "antworker004.hosts.typesofants.org:3241"
          - "antworker005.hosts.typesofants.org:3241"
          - "antworker006.hosts.typesofants.org:3241"
          - "antworker007.hosts.typesofants.org:3241"
        labels:
          group: "production"

      - targets:
          - "antworker002.hosts.typesofants.org:3241"
        labels:
          group: "beta"
