# [target.armv7-unknown-linux-gnueabihf]
# image = "ahuszagh/aarch64-cross:armv7-unknown-linux-gnueabihf"

# [target.aarch64-unknown-linux-gnu]
# image = "ahuszagh/aarch64-cross:aarch64-unknown-linux-gnu"
