services:
  ant-data-farm:
    image: ant-data-farm:${VERSION}
    container_name: ant-data-farm
    build:
      context: ./projects/ant-data-farm
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${ANT_DATA_FARM_PORT}:5432" # Map a types-of-ants port 7000 to the postgres default port 5432
    environment:
      VERSION: ${VERSION}
      POSTGRES_DB_FILE: /run/secrets/ant_data_farm_db
      POSTGRES_USER_FILE: /run/secrets/ant_data_farm_user
      POSTGRES_PASSWORD_FILE: /run/secrets/ant_data_farm_password
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ${PERSIST_DIR}/database-files/:/var/lib/postgresql/data
    secrets:
      - ant_data_farm_db
      - ant_data_farm_user
      - ant_data_farm_password

  ant-backing-it-up-storage:
    image: ant-backing-it-up-storage:${VERSION}
    container_name: ant-backing-it-up-storage
    build:
      context: ./projects/ant-backing-it-up-storage
      dockerfile: Dockerfile
      args:
        TYPESOFANTS_ENV: ${TYPESOFANTS_ENV}
    restart: always
    ports:
      - "${ANT_BACKING_IT_UP_STORAGE_PORT}:5432"
    environment:
      VERSION: ${VERSION}
      POSTGRES_DB_FILE: /run/secrets/ant_backing_it_up_storage_db
      POSTGRES_USER_FILE: /run/secrets/ant_backing_it_up_storage_user
      POSTGRES_PASSWORD_FILE: /run/secrets/ant_backing_it_up_storage_password
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ${PERSIST_DIR}/database-files/:/var/lib/postgresql/data
    secrets:
      - ant_backing_it_up_storage_db
      - ant_backing_it_up_storage_user
      - ant_backing_it_up_storage_password

  ant-zoo-storage:
    image: ant-zoo-storage:${VERSION}
    container_name: ant-zoo-storage
    build:
      context: ./projects/ant-zoo-storage
      dockerfile: Dockerfile
      args:
        TYPESOFANTS_ENV: ${TYPESOFANTS_ENV}
    restart: always
    ports:
      - "${ANT_ZOO_STORAGE_PORT}:5432"
    environment:
      VERSION: ${VERSION}
      POSTGRES_DB_FILE: /run/secrets/ant_zoo_storage_db
      POSTGRES_USER_FILE: /run/secrets/ant_zoo_storage_user
      POSTGRES_PASSWORD_FILE: /run/secrets/ant_zoo_storage_password
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ${PERSIST_DIR}/database-files/:/var/lib/postgresql/data
    secrets:
      - ant_zoo_storage_db
      - ant_zoo_storage_user
      - ant_zoo_storage_password

  ant-gateway:
    image: ant-gateway:${VERSION}
    container_name: ant-gateway
    build:
      context: ./projects/ant-gateway
      dockerfile: Dockerfile
      tags:
        - ant-gateway:latest
        - ant-gateway:${VERSION}
    restart: always
    environment:
      VERSION: ${VERSION}
      ANT_GATEWAY_FQDN: ${ANT_GATEWAY_FQDN}
      ANT_ON_THE_WEB_WORKER_NUM: ${ANT_ON_THE_WEB_WORKER_NUM}
      ANT_ON_THE_WEB_PORT: ${ANT_ON_THE_WEB_PORT}
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - tls_cert
      - tls_cert_key

  ant-renewing-certificates:
    image: ant-renewing-certificates:${VERSION}
    container_name: ant-renewing-certificates
    build:
      context: ./projects/ant-renewing-certificates
      dockerfile: Dockerfile
      args:
        - ANT_RENEWING_CERTIFICATES_FQDN=${ANT_RENEWING_CERTIFICATES_FQDN}
      tags:
        - ant-renewing-certificates:latest
        - ant-renewing-certificates:${VERSION}
    secrets:
      - cloudflare_api_token

  ant-naming-domains:
    image: linuxserver/ddclient:arm64v8-4.0.0
    platform: linux/arm64
    container_name: ant-naming-domains
    environment:
      VERSION: ${VERSION}
      ANT_NAMING_DOMAINS_FQDN: ${ANT_NAMING_DOMAINS_FQDN}
      PUID: 1001
      PGID: 1001
      TZ: Etc/UTC
      FILE__CLOUDFLARE_API_TOKEN: /run/secrets/cloudflare_api_token
    volumes:
      - ${INSTALL_DIR}/config:/config
    restart: always
    secrets:
      - cloudflare_api_token

  ant-fs:
    image: typesofants/ant-fs:arm64-latest
    platform: linux/arm64
    container_name: ant-fs
    environment:
      TYPESOFANTS_SECRET_DIR: /run/secrets
    restart: always
    volumes:
      - ${INSTALL_DIR}/fs:/app/fs
    ports:
      - 3237:3237
    secrets:
      - ant_fs_users.secret

secrets:
  ant_fs_users.secret:
    file: ${SECRETS_DIR}/ant_fs_users.secret

  ant_zoo_storage_db:
    file: ${SECRETS_DIR}/ant_zoo_storage_db.secret
  ant_zoo_storage_user:
    file: ${SECRETS_DIR}/ant_zoo_storage_user.secret
  ant_zoo_storage_password:
    file: ${SECRETS_DIR}/ant_zoo_storage_password.secret

  ant_backing_it_up_storage_db:
    file: ${SECRETS_DIR}/ant_backing_it_up_storage_db.secret
  ant_backing_it_up_storage_user:
    file: ${SECRETS_DIR}/ant_backing_it_up_storage_user.secret
  ant_backing_it_up_storage_password:
    file: ${SECRETS_DIR}/ant_backing_it_up_storage_password.secret

  ant_data_farm_db:
    file: ${SECRETS_DIR}/ant_data_farm_db.secret
  ant_data_farm_user:
    file: ${SECRETS_DIR}/ant_data_farm_user.secret
  ant_data_farm_password:
    file: ${SECRETS_DIR}/ant_data_farm_password.secret

  tls_cert:
    file: ${SECRETS_DIR}/tls_cert.pem
  tls_cert_key:
    file: ${SECRETS_DIR}/tls_key.pem
  cloudflare_api_token:
    file: ${SECRETS_DIR}/cloudflare.secret
