version: "3.7"

services:
  ant-data-farm:
    container_name: ant-data-farm
    build:
      context: ./projects/ant-data-farm
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7000:5432" # Map a types-of-ants port 7000 to the postgres default port 5432
    env_file: ./.env.db
    environment:
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./projects/ant-data-farm/database-files:/var/lib/postgresql/data
    secrets:
      - database_creds

  ant-gateway:
    container_name: ant-gateway
    build:
      context: ./projects/ant-gateway
      dockerfile: Dockerfile
      args:
        - FQDN=beta.typesofants.org
        - ANT_WORKER_NUM_ONE=002
        - ANT_WORKER_NUM_TWO=002
        - ANT_WORKER_NUM_THREE=002
        - WEBSERVER_PORT=3231
        - SSL_CERT_PATH=./data/beta.typesofants.org/cert.pem
        - SSL_KEY_PATH=./secrets/ssl/beta.typesofants.org/key.pem
    restart: always
    ports:
      - "80:80"
      - "443:443"

  ant-naming-domains:
    image: linuxserver/ddclient:arm64v8-4.0.0
    platform: linux/arm64
    container_name: ant-naming-domains
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - FILE__CLOUDFLARE_API_TOKEN=/run/secrets/cloudflare_api_token
    volumes:
      - ./projects/ant-naming-domains/config:/config
    restart: always
    secrets:
      - cloudflare_api_token

secrets:
  twitter_creds:
    file: ./.env.twitter
  database_creds:
    file: ./.env.db
  cloudflare_api_token:
    file: ./secrets/cloudflare_api_token.secret
