services:
  ant-data-farm:
    image: ant-data-farm:${VERSION}
    container_name: ant-data-farm
    build:
      context: ./projects/ant-data-farm
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7000:5432" # Map a types-of-ants port 7000 to the postgres default port 5432
    environment:
      VERSION: ${VERSION}
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ${PERSIST_DIR}/ant-data-farm/database-files/:/var/lib/postgresql/data
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

  ant-gateway:
    image: ant-gateway:${VERSION}
    container_name: ant-gateway
    build:
      context: ./projects/ant-gateway
      dockerfile: Dockerfile
      tags:
        - ant-gateway:latest
        - ant-gateway:${VERSION}
    restart: always
    environment:
      VERSION: ${VERSION}
      ANT_GATEWAY_FQDN: ${ANT_GATEWAY_FQDN}
      ANT_ON_THE_WEB_WORKER_NUM: ${ANT_ON_THE_WEB_WORKER_NUM}
      ANT_ON_THE_WEB_PORT: ${ANT_ON_THE_WEB_PORT}
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - tls_cert
      - tls_cert_key

  ant-renewing-certificates:
    image: ant-renewing-certificates:${VERSION}
    container_name: ant-renewing-certificates
    build:
      context: ./projects/ant-renewing-certificates
      dockerfile: Dockerfile
      args:
        - ANT_RENEWING_CERTIFICATES_FQDN=${ANT_RENEWING_CERTIFICATES_FQDN}
      tags:
        - ant-renewing-certificates:latest
        - ant-renewing-certificates:${VERSION}
    secrets:
      - cloudflare_api_token

  ant-naming-domains:
    image: linuxserver/ddclient:arm64v8-4.0.0
    platform: linux/arm64
    container_name: ant-naming-domains
    environment:
      VERSION: ${VERSION}
      ANT_NAMING_DOMAINS_FQDN: ${ANT_NAMING_DOMAINS_FQDN}
      PUID: 1001
      PGID: 1001
      TZ: Etc/UTC
      FILE__CLOUDFLARE_API_TOKEN: /run/secrets/cloudflare_api_token
    volumes:
      - ${INSTALL_DIR}/config:/config
    restart: always
    secrets:
      - cloudflare_api_token

secrets:
  postgres_db:
    file: ${INSTALL_DIR}/secrets/postgres_db.secret
  postgres_user:
    file: ${INSTALL_DIR}/secrets/postgres_user.secret
  postgres_password:
    file: ${INSTALL_DIR}/secrets/postgres_password.secret
  tls_cert:
    file: ${INSTALL_DIR}/secrets/tls_cert.pem
  tls_cert_key:
    file: ${INSTALL_DIR}/secrets/tls_key.pem
  cloudflare_api_token:
    file: ${INSTALL_DIR}/secrets/cloudflare.secret
