load("@rules_rust//rust:defs.bzl", "rust_binary")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "ant-building-projects",
    srcs = ["main.rs"],
    edition = "2021",
)
