[package]
name = "ant-releasing-ants-into-the-wild"
version = "0.1.0"
edition = "2024"

[dependencies]
ant-on-the-web = { version = "1.0.0", path = "../ant-on-the-web/server" }
clap = { version = "4.5.47", features = ["derive"] }
rand = "0.9.2"
reqwest = "0.12.23"
tokio = "1.47.1"
