[global]
address = "::"
port = 3499

[development]
address = "::"
port = 3501

# [global.tls]
# key = "/etc/letsencrypt/live/beta.typesofants.org/privkey.pem"
# certs = "/etc/letsencrypt/live/beta.typesofants.org/fullchain.pem"